### ISSUE TITLE
Error on tempColor

### ISSUE THREAD

**Issue by zoic21** [sqmk/Phue#100]
Hi,
I got an error on set color temp : 
````
invalid value, 177 }, for parameter, ct
````

Here my code : 
````
$command = new \Phue\Command\SetLightState(3);
$command->on(true);
$command->colorTemp(177);
$hue->sendCommand($command);
````

I don't understand why....

**Comment by sqmk** [comment]
What light model are you trying to update?

**Comment by zoic21** [comment]
It's from starter kit (E27 Color led) so maybe I don't have this. I need to check this, thank for your reponse

**Comment by sqmk** [comment]
If you can provide a dump for me that contains all of the following, that would help my investigation:
- $light->getType()
- $light->getModelId()
- $light->getModel()->getName()

**Comment by zoic21** [comment]
Here request informations : 
- Extended color light
- LCT001
- Hue bulb A19

Additional question : what is hue ? I test on my lamp and if it's white hue make it red but after that change of hue value do nothing....

**Comment by sqmk** [comment]
I'd suggest looking at the Philips Hue api documentation to understand what certain values will do for lights.

**Comment by zoic21** [comment]
Ok I understand. So I can close this.

**Comment by sqmk** [comment]
You can let me know what the lowest and highest value you can set on colorTemp on that bulb?

**Comment by zoic21** [comment]
I test 0 and 65535 and it's ok, I change from xy to hsv, for me it is more accurate (even if conversion hexa to hsv is not perfect)

**Comment by sqmk** [comment]
I'm asking what the lowest and highest values you can set for colorTemp (Mired Color), not for xy/hsv.
