### ISSUE TITLE
transition time limited?

### ISSUE THREAD

**Issue by mustberain** [sqmk/Phue#104]
Hi,

Awesome work, really easy to use and perfect for what I want. But.. always a but eh.
It seems like the transitiontime is limited for some reason, but i can not figure out why and what that time is.

this code:

```
$command = new \Phue\Command\SetLightState($light);
$command->brightness(85)
        ->hue(5211)
        ->saturation(254)
        ->transitionTime(10800);
$client->sendCommand(
        $command
);
```
shows: 

Fatal error: Uncaught exception 'Phue\Transport\Exception\InvalidValueException' with message 'invalid value, 108000}, for parameter, transitiontime'

Would be awesome if this can work, I like my light to get sleepy in the same time I do ;)

**Comment by sqmk** [comment]
Hey there @mustberain 

This appears to be a limitation with the Philips Hue bridge. Let me test and see what the threshold is on this value. Philips Hue API documentation isn't turning anything up on the max value of this.

**Comment by sqmk** [comment]
@mustberain 

Come to find out, the maximum transition time that can be provided directly to the bridge is 65535, which means a max value of 6553.5 via Phue. Phue converts transitionTime from seconds to 100 milliseconds to get to the bridge value of 65535. This value is roughly 1.82 hours.

You could get around the bridge limitation by setting a few scheduled timers.

**Comment by sqmk** [comment]
Unfortunately, there isn't much I can do to address this limitation. Feel free to close this ticket!

**Comment by sqmk** [comment]
Closing. Feel free to reopen this if you have any further questions, or if you have ideas on how to get around this limitation.
