### ISSUE TITLE
createGroup returns Undefined offset: 2

### ISSUE THREAD

**Issue by jonofe** [sqmk/Phue#108]
When calling new \Phue\Command\CreateGroup the error Undefined offset: 2 in line 104 is returned.
I checked the file

/Phue/library/Phue/Command/CreateGroup.php

It seems, that the resulting groupID is returned in $r[0] instead of $r[2].
After changing that, it works for me.

**Comment by sqmk** [comment]
Create a pull request with the change and I'll merge it in.

**Comment by sqmk** [comment]
Tagged as v1.5.1
