### ISSUE TITLE
isOn reports wrong state for offline lamps

### ISSUE THREAD

**Issue by openWebX** [sqmk/Phue#121]
Light->isOn() always returns true when lamps are completely off, that means not reachable...

I fixed the issue by rewriting the isOn-Method to 

```php
public function isOn()
    {
        return (bool) ($this->attributes->state->on && $this->attributes->state->reachable);
    }
```

**Comment by openWebX** [comment]
Another possible "fix" would be adding a "isReachable" method:

```php
    /**
     * Is the light reachable?
     *
     * @return bool True if reachable, false if not
     */
    public function isReachable() {
        return (bool) $this->attributes->state->reachable;
    }
```

**Comment by sgc-fireball** [comment]
+1

**Comment by sqmk** [comment]
These two states are different per bridge. isOn and isReachable should just return what the bridge is reporting. A different method should be implemented that uses both of those values for detecting real reachable state.
