### ISSUE TITLE
Update packagist version

### ISSUE THREAD

**Issue by topikito** [sqmk/Phue#91]
Hi,

In packagist, you have version 1.0 (January), but for example, that version does not include "isReachable" in the Lights class. Rather than using a "dev-master" version in my composer, I'd like to suggest the creation of version 1.1 as the library is stable.

**Comment by sqmk** [comment]
Sure, I can tag now.

**Comment by sqmk** [comment]
Tagged as v1.1.0. Should show up in packagist.

**Comment by topikito** [comment]
Thanks!
