### ISSUE TITLE
error with led strip

### ISSUE THREAD

**Issue by 889laurent** [sqmk/Phue#92]
when i use this command (getColorTemp()), i have this error
"temp couleur: PHP Notice:  Undefined property: stdClass::$ct in /var/www/hue2/vendor/sqmk/phue/library/Phue/Light.php on line 357"

the code
echo "id: " ,$light->getId(), "\n",
     "Name: ",$light->getName(), "\n",
     "Type: ",$light->getType(), "\n",
     "Modèle:" ,$light->getModelId(), "\n",
     "Version logiciel: ",$light->getSoftwareVersion(), "\n",
     "Allumé ?: ",$light->isOn(), "\n",
     "Alerte: ",$light->getAlert(), "\n",
     "Luminosité: ",$light->getBrightness(), "\n",
     "couleur hue: ",$light->getHue(), "\n",
     "saturation: ",$light->getSaturation(), "\n",
     "valeur X: ",$light->getXY()['x'], "\n",
     "valeur Y: ",$light->getXY()['y'], "\n",
     "effet: ",$light->getEffect(), "\n",
     "temp couleur: ",$light->getColorTemp(), "\n",
     "mode couleur: ",$light->getColorMode(), "\n",
     "\n";

result
id: 11
Name: Coline spot 6
Type: Extended color light
Modèle:LCT003
Version logiciel: 66013105
Allumé ?:
Alerte: none
Luminosité: 254
couleur hue: 48962
saturation: 16
valeur X: 0.3702
valeur Y: 0.3574
effet: none
temp couleur: 234
mode couleur: xy

id: 12
Name: Coline led
Type: Color light
Modèle:LST001
Version logiciel: 66013452
Allumé ?:
Alerte: none
Luminosité: 254
couleur hue: 37466
saturation: 137
valeur X: 0.2865
valeur Y: 0.3557
effet: none
temp couleur: PHP Notice:  Undefined property: stdClass::$ct in /var/www/hue2/vendor/sqmk/phue/library/Phue/Light.php on line 357

mode couleur: xy

id: 13
Name: Coline plafond
Type: Extended color light
Modèle:LCT001
Version logiciel: 66013452
Allumé ?: 1
Alerte: none
Luminosité: 254
couleur hue: 14910
saturation: 144
valeur X: 0.4596
valeur Y: 0.4105
effet: none
temp couleur: 369
mode couleur: ct

thanks for your help

**Comment by sqmk** [comment]
Interesting. Color temp may not be available for that model. I'll add some additional features to models to check for feature availability.
