### ISSUE TITLE
code with ie or firefox

### ISSUE THREAD

**Issue by 889laurent** [sqmk/Phue#93]
when i test this code on a internet navigator there not works ?  if i test on my RPI its ok

the code "<?php

require __DIR__ . '/vendor/autoload.php';
echo "test:";

$client = new \Phue\Client('192.168.0.225', 'laurentmario');
$group = $client->getGroups()[1];

$group->setOn(true);
echo "allumage ...<br/>";
?>
"

**Comment by sqmk** [comment]
This sounds like an implementation problem which is out of my control.

**Comment by 889laurent** [comment]
i have find my problem. Is read/write problem on files.
thanks
