### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [sqmk/Phue#95]
Hi Michael,

I work for Philips Hue Developer Support.  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

Am not a PHP developer myself, but I had a quick look at your code and in CreateUser.php your __construct method is passing the username.  After February 2016 this will no longer work so it should be removed.  The randomly generated bridge username will be returned in the bridge response (as per the above link).  Apologies for the inconvenience.

Thanks
Steve

**Comment by sqmk** [comment]
Thanks Steve. I'll make appropriate changes this week.

**Comment by SteveyO** [comment]
Thanks Michael,  Much appreciated!

**Comment by sqmk** [comment]
Tagged v1.2.0.

**Comment by SteveyO** [comment]
Fantastic.  Thanks for the fast fix!
Steve
