### ISSUE TITLE
Transition time on scene

### ISSUE THREAD

**Issue by zoic21** [sqmk/Phue#99]
Hi,
I can't make transition on scene, here my code : 
````
$command = new \Phue\Command\SetGroupState(0);
$command->scene($this->getConfiguration('id'));
$command->transitionTime($transistion_time);
print_r($command);
$hue->sendCommand($command);
````

Scene is launch but no transition but no transition, here phue object : 
````
Phue\Command\SetGroupState Object (     [groupId:protected] => 0     [lightId:protected] =>      [params:protected] => Array         (             [scene] => a296cf0d5-on-0             [transitiontime] => 300         )  ) 
````

Here I can see transitiontime so I dont understand where is my error...

THank in advance for your time

**Comment by sqmk** [comment]
Hi there,

When you recall a scene, I do not believe the transition time is applied.

**Comment by zoic21** [comment]
Hi,
Thank for your response. I am not sure but with philips hue app I can configure timer on scene with transistion time and it's work. So I think transistion is possible on scene.

**Comment by sqmk** [comment]
It appears that the Phue\Scene does not support setting transition time. Passing transition time on recalling with group won't work, so you'll need to register transition time on the scene instead.

I will add this functionality within a few minutes and push out a release.

**Comment by sqmk** [comment]
You can now set transition time as part of creating a scene in v1.3.0.

```php
$createScene = (new CreateScene('phue-test', 'Scene test', [1, 2]))
    ->transitionTime(2);
```

**Comment by zoic21** [comment]
I test this tonight or tomorrow thank for this update
